# Build-time git hash refresh.
#
# Runs every build (the consumer target depends on ALWAYS_RUN_THIS_TARGET) and
# regenerates ${OUTPUT_FILE} only when the short HEAD hash actually changes —
# so the resulting recompile triggers only on real commits, not on every
# `ninja` invocation.
#
# Called as: cmake -D OUTPUT_FILE=... -D SOURCE_DIR=... -P UpdateGitVersion.cmake
#
# Why this exists: SDCPP_GIT_COMMIT used to be captured by execute_process at
# configure time and passed as a -D compile flag. That meant `cmake --build`
# after new commits kept embedding the OLD hash into the binary — the
# /health endpoint's `git_commit` field would lie about which source tree
# produced the binary. Generating a tiny .cpp file at build time via this
# script fixes that: the file is a real translation unit ninja tracks for
# mtime, so any change in its contents triggers a recompile + relink.

if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "UpdateGitVersion: OUTPUT_FILE not set")
endif()
if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "UpdateGitVersion: SOURCE_DIR not set")
endif()

execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY ${SOURCE_DIR}
    OUTPUT_VARIABLE GIT_COMMIT
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)
if(NOT GIT_COMMIT)
    set(GIT_COMMIT "unknown")
endif()

# Detect a dirty working tree so the binary's git_commit can flag
# "this was built with uncommitted changes". The check is cheap (porcelain
# only inspects the index + worktree state) and skips when git itself isn't
# available.
execute_process(
    COMMAND git status --porcelain --untracked-files=no
    WORKING_DIRECTORY ${SOURCE_DIR}
    OUTPUT_VARIABLE GIT_DIRTY_LINES
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)
if(GIT_DIRTY_LINES)
    set(GIT_COMMIT "${GIT_COMMIT}-dirty")
endif()

set(CONTENT "// Auto-generated by cmake/UpdateGitVersion.cmake — do not edit.\n")
set(CONTENT "${CONTENT}// Regenerated on every build; recompiled only when the hash changes.\n")
set(CONTENT "${CONTENT}namespace sdcpp {\n")
set(CONTENT "${CONTENT}extern const char* const SDCPP_GIT_COMMIT_RUNTIME;\n")
set(CONTENT "${CONTENT}const char* const SDCPP_GIT_COMMIT_RUNTIME = \"${GIT_COMMIT}\";\n")
set(CONTENT "${CONTENT}}\n")

# Only rewrite when the content actually changed — keeps ninja from
# triggering a recompile/relink on every build invocation. configure_file
# would always touch the file; reading + comparing first avoids that.
set(REWRITE TRUE)
if(EXISTS ${OUTPUT_FILE})
    file(READ ${OUTPUT_FILE} OLD_CONTENT)
    if(OLD_CONTENT STREQUAL CONTENT)
        set(REWRITE FALSE)
    endif()
endif()
if(REWRITE)
    file(WRITE ${OUTPUT_FILE} "${CONTENT}")
    message(STATUS "Refreshed git commit: ${GIT_COMMIT}")
endif()
